//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ADM_WebSite.MyWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fill_FormOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fill_Coun_FormOperationCompleted;
        
        private System.Threading.SendOrPostCallback Stud_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Genrate_PassOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ask_Again_QueOperationCompleted;
        
        private System.Threading.SendOrPostCallback Load_ResponseOperationCompleted;
        
        private System.Threading.SendOrPostCallback Pre_Fill_ARFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ARF_FillOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateMarksOperationCompleted;
        
        private System.Threading.SendOrPostCallback PastEdu_Details_DipOperationCompleted;
        
        private System.Threading.SendOrPostCallback PastEdu_DetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Gen_AppidOperationCompleted;
        
        private System.Threading.SendOrPostCallback Pass_ResetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Upload_DocOperationCompleted;
        
        private System.Threading.SendOrPostCallback Doc_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback State_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback City_ListsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Clerk_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Pass_Reset_ClerkOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::ADM_WebSite.Properties.Settings.Default.ADM_WebSite_MyWebService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event Fill_FormCompletedEventHandler Fill_FormCompleted;
        
        /// <remarks/>
        public event Fill_Coun_FormCompletedEventHandler Fill_Coun_FormCompleted;
        
        /// <remarks/>
        public event Stud_LoginCompletedEventHandler Stud_LoginCompleted;
        
        /// <remarks/>
        public event Genrate_PassCompletedEventHandler Genrate_PassCompleted;
        
        /// <remarks/>
        public event Ask_Again_QueCompletedEventHandler Ask_Again_QueCompleted;
        
        /// <remarks/>
        public event Load_ResponseCompletedEventHandler Load_ResponseCompleted;
        
        /// <remarks/>
        public event Pre_Fill_ARFCompletedEventHandler Pre_Fill_ARFCompleted;
        
        /// <remarks/>
        public event ARF_FillCompletedEventHandler ARF_FillCompleted;
        
        /// <remarks/>
        public event CalculateMarksCompletedEventHandler CalculateMarksCompleted;
        
        /// <remarks/>
        public event PastEdu_Details_DipCompletedEventHandler PastEdu_Details_DipCompleted;
        
        /// <remarks/>
        public event PastEdu_DetailsCompletedEventHandler PastEdu_DetailsCompleted;
        
        /// <remarks/>
        public event Gen_AppidCompletedEventHandler Gen_AppidCompleted;
        
        /// <remarks/>
        public event Pass_ResetCompletedEventHandler Pass_ResetCompleted;
        
        /// <remarks/>
        public event Upload_DocCompletedEventHandler Upload_DocCompleted;
        
        /// <remarks/>
        public event Doc_ListCompletedEventHandler Doc_ListCompleted;
        
        /// <remarks/>
        public event State_ListCompletedEventHandler State_ListCompleted;
        
        /// <remarks/>
        public event City_ListsCompletedEventHandler City_ListsCompleted;
        
        /// <remarks/>
        public event Clerk_LoginCompletedEventHandler Clerk_LoginCompleted;
        
        /// <remarks/>
        public event Pass_Reset_ClerkCompletedEventHandler Pass_Reset_ClerkCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fill_Form", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fill_Form(EnqueryFields ef) {
            object[] results = this.Invoke("Fill_Form", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fill_FormAsync(EnqueryFields ef) {
            this.Fill_FormAsync(ef, null);
        }
        
        /// <remarks/>
        public void Fill_FormAsync(EnqueryFields ef, object userState) {
            if ((this.Fill_FormOperationCompleted == null)) {
                this.Fill_FormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFill_FormOperationCompleted);
            }
            this.InvokeAsync("Fill_Form", new object[] {
                        ef}, this.Fill_FormOperationCompleted, userState);
        }
        
        private void OnFill_FormOperationCompleted(object arg) {
            if ((this.Fill_FormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fill_FormCompleted(this, new Fill_FormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fill_Coun_Form", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Fill_Coun_Form(CounsellingFields ef) {
            object[] results = this.Invoke("Fill_Coun_Form", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Fill_Coun_FormAsync(CounsellingFields ef) {
            this.Fill_Coun_FormAsync(ef, null);
        }
        
        /// <remarks/>
        public void Fill_Coun_FormAsync(CounsellingFields ef, object userState) {
            if ((this.Fill_Coun_FormOperationCompleted == null)) {
                this.Fill_Coun_FormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFill_Coun_FormOperationCompleted);
            }
            this.InvokeAsync("Fill_Coun_Form", new object[] {
                        ef}, this.Fill_Coun_FormOperationCompleted, userState);
        }
        
        private void OnFill_Coun_FormOperationCompleted(object arg) {
            if ((this.Fill_Coun_FormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fill_Coun_FormCompleted(this, new Fill_Coun_FormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Stud_Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Stud_Login(StudLoginFields ef) {
            object[] results = this.Invoke("Stud_Login", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Stud_LoginAsync(StudLoginFields ef) {
            this.Stud_LoginAsync(ef, null);
        }
        
        /// <remarks/>
        public void Stud_LoginAsync(StudLoginFields ef, object userState) {
            if ((this.Stud_LoginOperationCompleted == null)) {
                this.Stud_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStud_LoginOperationCompleted);
            }
            this.InvokeAsync("Stud_Login", new object[] {
                        ef}, this.Stud_LoginOperationCompleted, userState);
        }
        
        private void OnStud_LoginOperationCompleted(object arg) {
            if ((this.Stud_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Stud_LoginCompleted(this, new Stud_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Genrate_Pass", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Genrate_Pass(StudLoginFields ef) {
            object[] results = this.Invoke("Genrate_Pass", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Genrate_PassAsync(StudLoginFields ef) {
            this.Genrate_PassAsync(ef, null);
        }
        
        /// <remarks/>
        public void Genrate_PassAsync(StudLoginFields ef, object userState) {
            if ((this.Genrate_PassOperationCompleted == null)) {
                this.Genrate_PassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenrate_PassOperationCompleted);
            }
            this.InvokeAsync("Genrate_Pass", new object[] {
                        ef}, this.Genrate_PassOperationCompleted, userState);
        }
        
        private void OnGenrate_PassOperationCompleted(object arg) {
            if ((this.Genrate_PassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Genrate_PassCompleted(this, new Genrate_PassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ask_Again_Que", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ask_Again_Que(EnqueryFields ef) {
            object[] results = this.Invoke("Ask_Again_Que", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Ask_Again_QueAsync(EnqueryFields ef) {
            this.Ask_Again_QueAsync(ef, null);
        }
        
        /// <remarks/>
        public void Ask_Again_QueAsync(EnqueryFields ef, object userState) {
            if ((this.Ask_Again_QueOperationCompleted == null)) {
                this.Ask_Again_QueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAsk_Again_QueOperationCompleted);
            }
            this.InvokeAsync("Ask_Again_Que", new object[] {
                        ef}, this.Ask_Again_QueOperationCompleted, userState);
        }
        
        private void OnAsk_Again_QueOperationCompleted(object arg) {
            if ((this.Ask_Again_QueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ask_Again_QueCompleted(this, new Ask_Again_QueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Load_Response", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Load_Response(EnqueryFields ef) {
            object[] results = this.Invoke("Load_Response", new object[] {
                        ef});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Load_ResponseAsync(EnqueryFields ef) {
            this.Load_ResponseAsync(ef, null);
        }
        
        /// <remarks/>
        public void Load_ResponseAsync(EnqueryFields ef, object userState) {
            if ((this.Load_ResponseOperationCompleted == null)) {
                this.Load_ResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoad_ResponseOperationCompleted);
            }
            this.InvokeAsync("Load_Response", new object[] {
                        ef}, this.Load_ResponseOperationCompleted, userState);
        }
        
        private void OnLoad_ResponseOperationCompleted(object arg) {
            if ((this.Load_ResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Load_ResponseCompleted(this, new Load_ResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pre_Fill_ARF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Pre_Fill_ARF(ARFFormFields ef) {
            object[] results = this.Invoke("Pre_Fill_ARF", new object[] {
                        ef});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Pre_Fill_ARFAsync(ARFFormFields ef) {
            this.Pre_Fill_ARFAsync(ef, null);
        }
        
        /// <remarks/>
        public void Pre_Fill_ARFAsync(ARFFormFields ef, object userState) {
            if ((this.Pre_Fill_ARFOperationCompleted == null)) {
                this.Pre_Fill_ARFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPre_Fill_ARFOperationCompleted);
            }
            this.InvokeAsync("Pre_Fill_ARF", new object[] {
                        ef}, this.Pre_Fill_ARFOperationCompleted, userState);
        }
        
        private void OnPre_Fill_ARFOperationCompleted(object arg) {
            if ((this.Pre_Fill_ARFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Pre_Fill_ARFCompleted(this, new Pre_Fill_ARFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ARF_Fill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ARF_Fill(ARFFormFields ef) {
            object[] results = this.Invoke("ARF_Fill", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ARF_FillAsync(ARFFormFields ef) {
            this.ARF_FillAsync(ef, null);
        }
        
        /// <remarks/>
        public void ARF_FillAsync(ARFFormFields ef, object userState) {
            if ((this.ARF_FillOperationCompleted == null)) {
                this.ARF_FillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnARF_FillOperationCompleted);
            }
            this.InvokeAsync("ARF_Fill", new object[] {
                        ef}, this.ARF_FillOperationCompleted, userState);
        }
        
        private void OnARF_FillOperationCompleted(object arg) {
            if ((this.ARF_FillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ARF_FillCompleted(this, new ARF_FillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateMarks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PastEduFields CalculateMarks(PastEduFields ef) {
            object[] results = this.Invoke("CalculateMarks", new object[] {
                        ef});
            return ((PastEduFields)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateMarksAsync(PastEduFields ef) {
            this.CalculateMarksAsync(ef, null);
        }
        
        /// <remarks/>
        public void CalculateMarksAsync(PastEduFields ef, object userState) {
            if ((this.CalculateMarksOperationCompleted == null)) {
                this.CalculateMarksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateMarksOperationCompleted);
            }
            this.InvokeAsync("CalculateMarks", new object[] {
                        ef}, this.CalculateMarksOperationCompleted, userState);
        }
        
        private void OnCalculateMarksOperationCompleted(object arg) {
            if ((this.CalculateMarksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateMarksCompleted(this, new CalculateMarksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PastEdu_Details_Dip", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PastEdu_Details_Dip(PastEduFields ef) {
            object[] results = this.Invoke("PastEdu_Details_Dip", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PastEdu_Details_DipAsync(PastEduFields ef) {
            this.PastEdu_Details_DipAsync(ef, null);
        }
        
        /// <remarks/>
        public void PastEdu_Details_DipAsync(PastEduFields ef, object userState) {
            if ((this.PastEdu_Details_DipOperationCompleted == null)) {
                this.PastEdu_Details_DipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPastEdu_Details_DipOperationCompleted);
            }
            this.InvokeAsync("PastEdu_Details_Dip", new object[] {
                        ef}, this.PastEdu_Details_DipOperationCompleted, userState);
        }
        
        private void OnPastEdu_Details_DipOperationCompleted(object arg) {
            if ((this.PastEdu_Details_DipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PastEdu_Details_DipCompleted(this, new PastEdu_Details_DipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PastEdu_Details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PastEdu_Details(PastEduFields ef) {
            object[] results = this.Invoke("PastEdu_Details", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PastEdu_DetailsAsync(PastEduFields ef) {
            this.PastEdu_DetailsAsync(ef, null);
        }
        
        /// <remarks/>
        public void PastEdu_DetailsAsync(PastEduFields ef, object userState) {
            if ((this.PastEdu_DetailsOperationCompleted == null)) {
                this.PastEdu_DetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPastEdu_DetailsOperationCompleted);
            }
            this.InvokeAsync("PastEdu_Details", new object[] {
                        ef}, this.PastEdu_DetailsOperationCompleted, userState);
        }
        
        private void OnPastEdu_DetailsOperationCompleted(object arg) {
            if ((this.PastEdu_DetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PastEdu_DetailsCompleted(this, new PastEdu_DetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Gen_Appid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Gen_Appid(EnqueryFields ff) {
            object[] results = this.Invoke("Gen_Appid", new object[] {
                        ff});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Gen_AppidAsync(EnqueryFields ff) {
            this.Gen_AppidAsync(ff, null);
        }
        
        /// <remarks/>
        public void Gen_AppidAsync(EnqueryFields ff, object userState) {
            if ((this.Gen_AppidOperationCompleted == null)) {
                this.Gen_AppidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGen_AppidOperationCompleted);
            }
            this.InvokeAsync("Gen_Appid", new object[] {
                        ff}, this.Gen_AppidOperationCompleted, userState);
        }
        
        private void OnGen_AppidOperationCompleted(object arg) {
            if ((this.Gen_AppidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Gen_AppidCompleted(this, new Gen_AppidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pass_Reset", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Pass_Reset(StudLoginFields ef) {
            object[] results = this.Invoke("Pass_Reset", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Pass_ResetAsync(StudLoginFields ef) {
            this.Pass_ResetAsync(ef, null);
        }
        
        /// <remarks/>
        public void Pass_ResetAsync(StudLoginFields ef, object userState) {
            if ((this.Pass_ResetOperationCompleted == null)) {
                this.Pass_ResetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPass_ResetOperationCompleted);
            }
            this.InvokeAsync("Pass_Reset", new object[] {
                        ef}, this.Pass_ResetOperationCompleted, userState);
        }
        
        private void OnPass_ResetOperationCompleted(object arg) {
            if ((this.Pass_ResetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Pass_ResetCompleted(this, new Pass_ResetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Upload_Doc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Upload_Doc(DocumentFields ef) {
            object[] results = this.Invoke("Upload_Doc", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Upload_DocAsync(DocumentFields ef) {
            this.Upload_DocAsync(ef, null);
        }
        
        /// <remarks/>
        public void Upload_DocAsync(DocumentFields ef, object userState) {
            if ((this.Upload_DocOperationCompleted == null)) {
                this.Upload_DocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpload_DocOperationCompleted);
            }
            this.InvokeAsync("Upload_Doc", new object[] {
                        ef}, this.Upload_DocOperationCompleted, userState);
        }
        
        private void OnUpload_DocOperationCompleted(object arg) {
            if ((this.Upload_DocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Upload_DocCompleted(this, new Upload_DocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Doc_List", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Doc_List() {
            object[] results = this.Invoke("Doc_List", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Doc_ListAsync() {
            this.Doc_ListAsync(null);
        }
        
        /// <remarks/>
        public void Doc_ListAsync(object userState) {
            if ((this.Doc_ListOperationCompleted == null)) {
                this.Doc_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoc_ListOperationCompleted);
            }
            this.InvokeAsync("Doc_List", new object[0], this.Doc_ListOperationCompleted, userState);
        }
        
        private void OnDoc_ListOperationCompleted(object arg) {
            if ((this.Doc_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Doc_ListCompleted(this, new Doc_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/State_List", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet State_List() {
            object[] results = this.Invoke("State_List", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void State_ListAsync() {
            this.State_ListAsync(null);
        }
        
        /// <remarks/>
        public void State_ListAsync(object userState) {
            if ((this.State_ListOperationCompleted == null)) {
                this.State_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnState_ListOperationCompleted);
            }
            this.InvokeAsync("State_List", new object[0], this.State_ListOperationCompleted, userState);
        }
        
        private void OnState_ListOperationCompleted(object arg) {
            if ((this.State_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.State_ListCompleted(this, new State_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/City_Lists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet City_Lists(int s) {
            object[] results = this.Invoke("City_Lists", new object[] {
                        s});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void City_ListsAsync(int s) {
            this.City_ListsAsync(s, null);
        }
        
        /// <remarks/>
        public void City_ListsAsync(int s, object userState) {
            if ((this.City_ListsOperationCompleted == null)) {
                this.City_ListsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCity_ListsOperationCompleted);
            }
            this.InvokeAsync("City_Lists", new object[] {
                        s}, this.City_ListsOperationCompleted, userState);
        }
        
        private void OnCity_ListsOperationCompleted(object arg) {
            if ((this.City_ListsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.City_ListsCompleted(this, new City_ListsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Clerk_Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Clerk_Login(ClearkLoginFields ef) {
            object[] results = this.Invoke("Clerk_Login", new object[] {
                        ef});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Clerk_LoginAsync(ClearkLoginFields ef) {
            this.Clerk_LoginAsync(ef, null);
        }
        
        /// <remarks/>
        public void Clerk_LoginAsync(ClearkLoginFields ef, object userState) {
            if ((this.Clerk_LoginOperationCompleted == null)) {
                this.Clerk_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClerk_LoginOperationCompleted);
            }
            this.InvokeAsync("Clerk_Login", new object[] {
                        ef}, this.Clerk_LoginOperationCompleted, userState);
        }
        
        private void OnClerk_LoginOperationCompleted(object arg) {
            if ((this.Clerk_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Clerk_LoginCompleted(this, new Clerk_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pass_Reset_Clerk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Pass_Reset_Clerk(ClearkLoginFields ef) {
            object[] results = this.Invoke("Pass_Reset_Clerk", new object[] {
                        ef});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Pass_Reset_ClerkAsync(ClearkLoginFields ef) {
            this.Pass_Reset_ClerkAsync(ef, null);
        }
        
        /// <remarks/>
        public void Pass_Reset_ClerkAsync(ClearkLoginFields ef, object userState) {
            if ((this.Pass_Reset_ClerkOperationCompleted == null)) {
                this.Pass_Reset_ClerkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPass_Reset_ClerkOperationCompleted);
            }
            this.InvokeAsync("Pass_Reset_Clerk", new object[] {
                        ef}, this.Pass_Reset_ClerkOperationCompleted, userState);
        }
        
        private void OnPass_Reset_ClerkOperationCompleted(object arg) {
            if ((this.Pass_Reset_ClerkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Pass_Reset_ClerkCompleted(this, new Pass_Reset_ClerkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EnqueryFields {
        
        private int appIDField;
        
        private string uidField;
        
        private string phnoField;
        
        private string fNameField;
        
        private string mNameField;
        
        private string lNameField;
        
        private string emailField;
        
        private string stateField;
        
        private string cityField;
        
        private string queryField;
        
        /// <remarks/>
        public int AppID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        public string Uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string Phno {
            get {
                return this.phnoField;
            }
            set {
                this.phnoField = value;
            }
        }
        
        /// <remarks/>
        public string FName {
            get {
                return this.fNameField;
            }
            set {
                this.fNameField = value;
            }
        }
        
        /// <remarks/>
        public string MName {
            get {
                return this.mNameField;
            }
            set {
                this.mNameField = value;
            }
        }
        
        /// <remarks/>
        public string LName {
            get {
                return this.lNameField;
            }
            set {
                this.lNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClearkLoginFields {
        
        private string emailField;
        
        private string passField;
        
        private string oldPassField;
        
        private string confirmPassField;
        
        private string clerkIDField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
            }
        }
        
        /// <remarks/>
        public string OldPass {
            get {
                return this.oldPassField;
            }
            set {
                this.oldPassField = value;
            }
        }
        
        /// <remarks/>
        public string ConfirmPass {
            get {
                return this.confirmPassField;
            }
            set {
                this.confirmPassField = value;
            }
        }
        
        /// <remarks/>
        public string ClerkID {
            get {
                return this.clerkIDField;
            }
            set {
                this.clerkIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DocumentFields {
        
        private string docNameField;
        
        private int appIDField;
        
        private int docIDField;
        
        private string docPathField;
        
        /// <remarks/>
        public string DocName {
            get {
                return this.docNameField;
            }
            set {
                this.docNameField = value;
            }
        }
        
        /// <remarks/>
        public int AppID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        public int DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
            }
        }
        
        /// <remarks/>
        public string DocPath {
            get {
                return this.docPathField;
            }
            set {
                this.docPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PastEduFields {
        
        private int sscOutOfField;
        
        private int doutofField;
        
        private int appIDField;
        
        private string hsscBoardField;
        
        private string hsscGradeField;
        
        private int hsscPhyField;
        
        private int hsscChemField;
        
        private int hsscMathsField;
        
        private int hsscPcmTotField;
        
        private int hsscTotMarksObtField;
        
        private int hsscTotMarksField;
        
        private float hsscPcmPerField;
        
        private float hsscOverallPerField;
        
        private int sscTotObtField;
        
        private string sscBoardField;
        
        private float sscOverallPerField;
        
        private int dipTotObtField;
        
        private string dipBoardField;
        
        private float dipOverallPerField;
        
        private int jeeScoreField;
        
        private string jeeRollField;
        
        private int cetScoreField;
        
        private string cetRollField;
        
        /// <remarks/>
        public int SscOutOf {
            get {
                return this.sscOutOfField;
            }
            set {
                this.sscOutOfField = value;
            }
        }
        
        /// <remarks/>
        public int Doutof {
            get {
                return this.doutofField;
            }
            set {
                this.doutofField = value;
            }
        }
        
        /// <remarks/>
        public int AppID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        public string HsscBoard {
            get {
                return this.hsscBoardField;
            }
            set {
                this.hsscBoardField = value;
            }
        }
        
        /// <remarks/>
        public string HsscGrade {
            get {
                return this.hsscGradeField;
            }
            set {
                this.hsscGradeField = value;
            }
        }
        
        /// <remarks/>
        public int HsscPhy {
            get {
                return this.hsscPhyField;
            }
            set {
                this.hsscPhyField = value;
            }
        }
        
        /// <remarks/>
        public int HsscChem {
            get {
                return this.hsscChemField;
            }
            set {
                this.hsscChemField = value;
            }
        }
        
        /// <remarks/>
        public int HsscMaths {
            get {
                return this.hsscMathsField;
            }
            set {
                this.hsscMathsField = value;
            }
        }
        
        /// <remarks/>
        public int HsscPcmTot {
            get {
                return this.hsscPcmTotField;
            }
            set {
                this.hsscPcmTotField = value;
            }
        }
        
        /// <remarks/>
        public int HsscTotMarksObt {
            get {
                return this.hsscTotMarksObtField;
            }
            set {
                this.hsscTotMarksObtField = value;
            }
        }
        
        /// <remarks/>
        public int HsscTotMarks {
            get {
                return this.hsscTotMarksField;
            }
            set {
                this.hsscTotMarksField = value;
            }
        }
        
        /// <remarks/>
        public float HsscPcmPer {
            get {
                return this.hsscPcmPerField;
            }
            set {
                this.hsscPcmPerField = value;
            }
        }
        
        /// <remarks/>
        public float HsscOverallPer {
            get {
                return this.hsscOverallPerField;
            }
            set {
                this.hsscOverallPerField = value;
            }
        }
        
        /// <remarks/>
        public int SscTotObt {
            get {
                return this.sscTotObtField;
            }
            set {
                this.sscTotObtField = value;
            }
        }
        
        /// <remarks/>
        public string SscBoard {
            get {
                return this.sscBoardField;
            }
            set {
                this.sscBoardField = value;
            }
        }
        
        /// <remarks/>
        public float SscOverallPer {
            get {
                return this.sscOverallPerField;
            }
            set {
                this.sscOverallPerField = value;
            }
        }
        
        /// <remarks/>
        public int DipTotObt {
            get {
                return this.dipTotObtField;
            }
            set {
                this.dipTotObtField = value;
            }
        }
        
        /// <remarks/>
        public string DipBoard {
            get {
                return this.dipBoardField;
            }
            set {
                this.dipBoardField = value;
            }
        }
        
        /// <remarks/>
        public float DipOverallPer {
            get {
                return this.dipOverallPerField;
            }
            set {
                this.dipOverallPerField = value;
            }
        }
        
        /// <remarks/>
        public int JeeScore {
            get {
                return this.jeeScoreField;
            }
            set {
                this.jeeScoreField = value;
            }
        }
        
        /// <remarks/>
        public string JeeRoll {
            get {
                return this.jeeRollField;
            }
            set {
                this.jeeRollField = value;
            }
        }
        
        /// <remarks/>
        public int CetScore {
            get {
                return this.cetScoreField;
            }
            set {
                this.cetScoreField = value;
            }
        }
        
        /// <remarks/>
        public string CetRoll {
            get {
                return this.cetRollField;
            }
            set {
                this.cetRollField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ARFFormFields {
        
        private string categoryField;
        
        private string uidField;
        
        private string phnoField;
        
        private string fNameField;
        
        private string mNameField;
        
        private string lNameField;
        
        private string emailField;
        
        private string stateField;
        
        private string cityField;
        
        private string streamField;
        
        private int appIDField;
        
        private string dOBField;
        
        private string genderField;
        
        private string faNameField;
        
        private string moNameField;
        
        private string faWorkField;
        
        private string moWorkField;
        
        private string faPhnoField;
        
        private string moPhnoField;
        
        private string incomeField;
        
        private string castField;
        
        private string religionField;
        
        private string addLine1Field;
        
        private string addLine2Field;
        
        private string addLine3Field;
        
        private string admissionTypeField;
        
        private string academicYearField;
        
        private string admissionInField;
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string Uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string Phno {
            get {
                return this.phnoField;
            }
            set {
                this.phnoField = value;
            }
        }
        
        /// <remarks/>
        public string FName {
            get {
                return this.fNameField;
            }
            set {
                this.fNameField = value;
            }
        }
        
        /// <remarks/>
        public string MName {
            get {
                return this.mNameField;
            }
            set {
                this.mNameField = value;
            }
        }
        
        /// <remarks/>
        public string LName {
            get {
                return this.lNameField;
            }
            set {
                this.lNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Stream {
            get {
                return this.streamField;
            }
            set {
                this.streamField = value;
            }
        }
        
        /// <remarks/>
        public int AppID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string FaName {
            get {
                return this.faNameField;
            }
            set {
                this.faNameField = value;
            }
        }
        
        /// <remarks/>
        public string MoName {
            get {
                return this.moNameField;
            }
            set {
                this.moNameField = value;
            }
        }
        
        /// <remarks/>
        public string FaWork {
            get {
                return this.faWorkField;
            }
            set {
                this.faWorkField = value;
            }
        }
        
        /// <remarks/>
        public string MoWork {
            get {
                return this.moWorkField;
            }
            set {
                this.moWorkField = value;
            }
        }
        
        /// <remarks/>
        public string FaPhno {
            get {
                return this.faPhnoField;
            }
            set {
                this.faPhnoField = value;
            }
        }
        
        /// <remarks/>
        public string MoPhno {
            get {
                return this.moPhnoField;
            }
            set {
                this.moPhnoField = value;
            }
        }
        
        /// <remarks/>
        public string Income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
            }
        }
        
        /// <remarks/>
        public string Cast {
            get {
                return this.castField;
            }
            set {
                this.castField = value;
            }
        }
        
        /// <remarks/>
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public string AddLine1 {
            get {
                return this.addLine1Field;
            }
            set {
                this.addLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddLine2 {
            get {
                return this.addLine2Field;
            }
            set {
                this.addLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string AddLine3 {
            get {
                return this.addLine3Field;
            }
            set {
                this.addLine3Field = value;
            }
        }
        
        /// <remarks/>
        public string AdmissionType {
            get {
                return this.admissionTypeField;
            }
            set {
                this.admissionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AcademicYear {
            get {
                return this.academicYearField;
            }
            set {
                this.academicYearField = value;
            }
        }
        
        /// <remarks/>
        public string AdmissionIn {
            get {
                return this.admissionInField;
            }
            set {
                this.admissionInField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StudLoginFields {
        
        private string emailField;
        
        private string passField;
        
        private string oldPassField;
        
        private string confirmPassField;
        
        private int appIDField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
            }
        }
        
        /// <remarks/>
        public string OldPass {
            get {
                return this.oldPassField;
            }
            set {
                this.oldPassField = value;
            }
        }
        
        /// <remarks/>
        public string ConfirmPass {
            get {
                return this.confirmPassField;
            }
            set {
                this.confirmPassField = value;
            }
        }
        
        /// <remarks/>
        public int AppID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CounsellingFields {
        
        private int appIdField;
        
        private string yearField;
        
        private string emailField;
        
        private string dateField;
        
        private string modeField;
        
        private string slotField;
        
        /// <remarks/>
        public int AppId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
            }
        }
        
        /// <remarks/>
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public string Slot {
            get {
                return this.slotField;
            }
            set {
                this.slotField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Fill_FormCompletedEventHandler(object sender, Fill_FormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fill_FormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fill_FormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Fill_Coun_FormCompletedEventHandler(object sender, Fill_Coun_FormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fill_Coun_FormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fill_Coun_FormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Stud_LoginCompletedEventHandler(object sender, Stud_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Stud_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Stud_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Genrate_PassCompletedEventHandler(object sender, Genrate_PassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Genrate_PassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Genrate_PassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Ask_Again_QueCompletedEventHandler(object sender, Ask_Again_QueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ask_Again_QueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ask_Again_QueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Load_ResponseCompletedEventHandler(object sender, Load_ResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Load_ResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Load_ResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Pre_Fill_ARFCompletedEventHandler(object sender, Pre_Fill_ARFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pre_Fill_ARFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Pre_Fill_ARFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ARF_FillCompletedEventHandler(object sender, ARF_FillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ARF_FillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ARF_FillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CalculateMarksCompletedEventHandler(object sender, CalculateMarksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateMarksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateMarksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PastEduFields Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PastEduFields)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PastEdu_Details_DipCompletedEventHandler(object sender, PastEdu_Details_DipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PastEdu_Details_DipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PastEdu_Details_DipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PastEdu_DetailsCompletedEventHandler(object sender, PastEdu_DetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PastEdu_DetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PastEdu_DetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Gen_AppidCompletedEventHandler(object sender, Gen_AppidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Gen_AppidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Gen_AppidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Pass_ResetCompletedEventHandler(object sender, Pass_ResetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pass_ResetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Pass_ResetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Upload_DocCompletedEventHandler(object sender, Upload_DocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Upload_DocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Upload_DocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Doc_ListCompletedEventHandler(object sender, Doc_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Doc_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Doc_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void State_ListCompletedEventHandler(object sender, State_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class State_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal State_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void City_ListsCompletedEventHandler(object sender, City_ListsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class City_ListsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal City_ListsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Clerk_LoginCompletedEventHandler(object sender, Clerk_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Clerk_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Clerk_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Pass_Reset_ClerkCompletedEventHandler(object sender, Pass_Reset_ClerkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pass_Reset_ClerkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Pass_Reset_ClerkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591